session_name: 'python-books-cli'
windows:
- focus: 'true'
  layout: 673a,178x46,0,0[178x33,0,0{89x33,0,0,0,88x33,90,0,2},178x12,0,34,1]
  options: {}
  panes:
  - focus: 'true'
    shell-command: zsh
  - zsh
  - zsh
  start_directory: /Users/josephgurr/Development/python-books-cli
  window_name: zsh
